### ISSUE TITLE
Feature request: Select list item by mouse click

### ISSUE THREAD

**Issue by simarust** [balazs4/windowswitcher#1]

**Comment by L0rdKlappstuhl** [comment]
Hi Shall the windowswitcher directly activate the window on a mouse click or only select it the item which then will be activated by a return?

**Comment by simarust** [comment]
I'd prefer the direct activation like in a web link.

**Comment by L0rdKlappstuhl** [comment]
Check out version 1.04 please should be working in the draft.

**Comment by balazs4** [comment]
v1.0.8 is public release and it includes the requested feature by @simarust
